[book]
authors = ["Gabor Szabo"]
language = "en"
src = "src"
title = "JavaScript Programming"
# "description": "JavaScript tutorial and training course for front-end developers who would like to understand what they do.",

# Add github icon to the menu
[output.html]
git-repository-url = "https://github.com/szabgab/front.code-maven.com"
git-repository-icon = "fas-code-fork"
edit-url-template = "https://github.com/szabgab/front.code-maven.com/edit/main/books/javascript/{path}"

[output.markdown]

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"




